2024-11-02 01:54:19.399 | ERROR    | door.config:find_commands:28 - Failed to import plugin 'door.commands.astro'
Traceback (most recent call last):

  File "/home/mike/mtdoor/./mtdoor.py", line 51, in <module>
    available_commands = find_commands(settings)
                         │             └ <configparser.ConfigParser object at 0x7fb8771990>
                         └ <function find_commands at 0x7fb85789a0>

> File "/home/mike/mtdoor/door/config.py", line 26, in find_commands
    module = importlib.import_module(section)
             │         │             └ 'door.commands.astro'
             │         └ <function import_module at 0x7fbaf7d4e0>
             └ <module 'importlib' from '/usr/lib/python3.11/importlib/__init__.py'>

  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'door.commands.astro'
           │          └ <function _gcd_import at 0x7fbb287d80>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/mike/mtdoor/door/commands/astro.py", line 3, in <module>
    import numpy as np

  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/numpy/_core/__init__.py", line 100, in <module>
    from . import _internal
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/numpy/_core/_internal.py", line 17, in <module>
    import ctypes
  File "/usr/lib/python3.11/ctypes/__init__.py", line 156, in <module>
    class py_object(_SimpleCData):
                    └ <class '_ctypes._SimpleCData'>

KeyboardInterrupt
2024-11-02 01:54:20.421 | DEBUG    | __main__:<module>:52 - Found 9 available commands: ['Ping', 'Msg', 'Firmware', 'Weather', 'Weather', 'Fortune', 'ChatGPT', 'NodeQuery', 'MeshLogger']
Traceback (most recent call last):
  File "/home/mike/mtdoor/./mtdoor.py", line 83, in <module>
    interface = SerialInterface(args.serial)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/meshtastic/serial_interface.py", line 65, in __init__
    StreamInterface.__init__(
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 51, in __init__
    self.connect()
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 75, in connect
    self._waitConnected()
  File "/home/mike/mtdoor/.venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 860, in _waitConnected
    if not self.isConnected.wait(timeout):  # timeout after x seconds
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
